@BaseURL = http://127.0.0.1:8000


####
# @name getAll
GET {{BaseURL}}/api/agendamento

####
# @name getOne
GET {{BaseURL}}/api/agendamento/2


####
# @name create
POST {{BaseURL}}/api/agendamento
Content-Type: application/json

{   
    //"week_day": "3",
    "teacher_id": 2,
    "resource_id": 2,
    "day_shift": 2,
    "time": 2,
    "loan_note": "pegando emprestimo",
    "class_room": "cc8"
}

####
# @name update
PUT {{BaseURL}}/api/agendamento/1
tent-Type: application/json

{
   "loan_note": "bla"
}

####
# @name delete
DELETE {{BaseURL}}/api/agendamento/2