@BaseURL = http://127.0.0.1:8000


####
# @name getAll
GET {{BaseURL}}/api/agendamento

####
# @name getOne
GET {{BaseURL}}/api/agendamento/1


####
# @name create
POST {{BaseURL}}/api/agendamento
Content-Type: application/json

{
    "teacher": 1,
    "resource": 1,
    "lead_date": "29/07/2021",
    "lead_return": "01/08/2021",
    "lead_days": ""
}