@BaseURL = http://127.0.0.1:9000


####
# @name getAll
GET {{BaseURL}}/api/reservas

####
# @name getOne
GET {{BaseURL}}/api/reserva/2


####
# @name create
POST {{BaseURL}}/api/reservas
Content-Type: application/json

{
    "teacher_id": 2,
    "resource_id": 3
}


####
# @name delete
DELETE {{BaseURL}}/api/reserva/6