@BaseURL = http://127.0.0.1:8000

####
# @name getAll
GET {{BaseURL}}/api/professor


####
# @name getOne
GET {{BaseURL}}/api/professor/17


####
# @name create
POST {{BaseURL}}/api/professor
tent-Type: application/json

{
    "name": "Francisco",
    "email": "Francisco@gmail.com",
    "phone": "434354"
}

####
# @name update
PUT {{BaseURL}}/api/professor/19
tent-Type: application/json

{
    "name": "Edwisley Ribeiro"
}


####
# @name delete
DELETE {{BaseURL}}/api/professor/19









