@BaseURL = http://127.0.0.1:9000

####
# @name getAll
GET {{BaseURL}}/api/professor


####
# @name getOne
GET {{BaseURL}}/api/professor/3


####
# @name create
POST {{BaseURL}}/api/professor
tent-Type: application/json

{
    "name": "francisco",
    "email": "francisco@gmail.com",
    "phone": "323"
}

####
# @name update
PUT {{BaseURL}}/api/professor/5
tent-Type: application/json

{
    "name": "Gerlane"  
}

####
# @name delete
DELETE {{BaseURL}}/api/professor/10










