@BaseURL = http://127.0.0.1:8000

####
# @name getAll
GET {{BaseURL}}/api/recurso


####
# @name getOne
GET {{BaseURL}}/api/recurso/1


####
# @name create
POST {{BaseURL}}/api/recurso
tent-Type: Application/json

{
    "name": "Data show",
    "patrimony_number": "3456"
}

####
# @name update
PUT {{BaseURL}}/api/recurso/1
tent-Type: application/json

{
    "name": "Data show",
    "patrimony_number": "3445"

}


####
# @name delete
DELETE {{BaseURL}}/api/recurso/









