@BaseURL = http://127.0.0.1:8000

####
# @name getAll
GET {{BaseURL}}/api/recursos


####
# @name getOne
GET {{BaseURL}}/api/recurso/1


####
# @name create
POST {{BaseURL}}/api/recursos
tent-Type: application/json

{
    "name": "Data Show"
}

####
# @name update
PUT {{BaseURL}}/api/recurso/2
tent-Type: application/json

{
    "name": "Data Show 2"
}


####
# @name delete
DELETE {{BaseURL}}/api/recurso/2









