@BaseURL = http://127.0.0.1:9000

####
# @name getAll
GET {{BaseURL}}/api/recursos


####
# @name getOne
GET {{BaseURL}}/api/recurso/1


####
# @name create
POST {{BaseURL}}/api/recursos
tent-Type: application/json

{
    "name": "Data show 14",
    "patrimony_number": "2334433"
}

####
# @name update
PUT {{BaseURL}}/api/recurso/1
tent-Type: application/json

{
    "loan_resource_id": 1

}


####
# @name delete
DELETE {{BaseURL}}/api/recursos/









