# Generated by Django 3.2.5 on 2021-08-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('patrimony_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceAuditorio',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recurso.resource')),
            ],
            bases=('recurso.resource',),
        ),
        migrations.CreateModel(
            name='ResourceCaixaSom',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recurso.resource')),
            ],
            bases=('recurso.resource',),
        ),
        migrations.CreateModel(
            name='ResourceDataShow',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recurso.resource')),
            ],
            bases=('recurso.resource',),
        ),
        migrations.CreateModel(
            name='ResourceQuadra',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recurso.resource')),
            ],
            bases=('recurso.resource',),
        ),
        migrations.CreateModel(
            name='LoanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date', models.DateField(auto_now=True)),
                ('day_shift', models.SmallIntegerField(choices=[(1, 'Noite'), (2, 'Manha')])),
                ('class_room', models.CharField(max_length=4, null=True)),
                ('time', models.SmallIntegerField(choices=[(1, 'Primeiro Horario'), (2, 'Segundo Horario')], null=True)),
                ('loan_note', models.CharField(max_length=200, null=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='recurso.resource')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='recurso.teacher')),
            ],
            options={
                'verbose_name': 'Agendamentos',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='LoanLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.SmallIntegerField(choices=[(1, 'teacher'), (2, 'resource'), (3, 'loan_resource')])),
                ('loan_resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='recurso.loanresource')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loanlogs', to='recurso.resource')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='recurso.teacher')),
            ],
        ),
    ]
