# Generated by Django 3.2.5 on 2021-07-29 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_date', models.DateField(auto_now=True)),
                ('lead_return', models.DateField(auto_now=True)),
                ('lead_days', models.SmallIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recurso.resource')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='recurso.teacher')),
            ],
        ),
    ]
