# Generated by Django 3.2.5 on 2021-08-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanresource',
            name='class_room',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
