# Generated by Django 3.2.5 on 2021-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0002_loanresource_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanresource',
            name='time',
            field=models.SmallIntegerField(choices=[(1, 'Primeiro Horario'), (2, 'Segundo Horario')], null=True),
        ),
    ]
