# Generated by Django 3.2.5 on 2021-08-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0003_loanresource_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanresource',
            name='loan_note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
